apiVersion: v1
kind: Pod
metadata:
  name: my-gpu-pod
spec:
  containers:
  - name: my-gpu-container
    # europe-west2-docker.pkg.dev/nlp-dev-6aae/nle-repo/11.0.3-runtime-ubuntu20.04
    image: europe-west2-docker.pkg.dev/nlp-dev-6aae/nle-repo/11.0.3-runtime-ubuntu20.04 # URL Taken from Artifact Registry
    command: ["/bin/bash", "-c", "--"]
    args: ["while true; do sleep 600; done;"]
    resources: # Below this line is limits confog which associated with GPU
      limits:
       nvidia.com/gpu: 1